import { Assistant } from './types';

export const ASSISTANTS: Assistant[] = [
  {
    id: 'gemini',
    name: 'Gemini',
    description: 'Google\'s most capable AI model.',
    url: 'https://gemini.google.com',
    icon: 'Sparkles',
    color: '#38abf8',
    isBuiltIn: true,
  },
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    description: 'OpenAI\'s versatile conversational AI.',
    url: 'https://chat.openai.com',
    icon: 'MessageSquare',
    color: '#10a37f',
  },
  {
    id: 'claude',
    name: 'Claude',
    description: 'Anthropic\'s helpful and honest assistant.',
    url: 'https://claude.ai',
    icon: 'Bot',
    color: '#d97757',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    description: 'AI-powered search engine.',
    url: 'https://perplexity.ai',
    icon: 'Search',
    color: '#20b2aa',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    description: 'Advanced AI from DeepSeek.',
    url: 'https://chat.deepseek.com',
    icon: 'Cpu',
    color: '#4f46e5',
  },
  {
    id: 'grok',
    name: 'Grok',
    description: 'xAI\'s witty and rebellious assistant.',
    url: 'https://x.ai',
    icon: 'Zap',
    color: '#000000',
  },
  {
    id: 'github',
    name: 'GitHub',
    description: 'Source code hosting and version control.',
    url: 'https://github.com',
    icon: 'Github',
    color: '#24292e',
    tabType: 'GIT',
  },
  {
    id: 'duckduckgo',
    name: 'Research',
    description: 'Privacy-focused search for deep research.',
    url: 'https://duckduckgo.com',
    icon: 'Search',
    color: '#de5833',
    tabType: 'RESEARCH',
  },
];
